<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "bolius_staticdomain"
 *
 * Auto generated by Extension Builder 2013-04-25
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
    'title'            => 'Bolius Static Domain',
    'description'      => '',
    'category'         => 'frontend',
    'author'           => 'Bolius Digital',
    'author_email'     => 'web@bolius.dk',
    'author_company'   => 'Bolius',
    'shy'              => '',
    'priority'         => '',
    'module'           => '',
    'state'            => 'alpha',
    'internal'         => '',
    'uploadfolder'     => '0',
    'createDirs'       => '',
    'modify_tables'    => '',
    'clearCacheOnLoad' => 0,
    'lockType'         => '',
    'version'          => '0.0.1',
    'constraints'      => array(
        'depends'   => array(
            'typo3'   => '6.0.0-9.9.99',
        ),
        'conflicts' => array(),
        'suggests'  => array(
        ),
    ),
);

?>
