<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "bolius_staticdomain"
 *
 * Auto generated by Extension Builder 2013-04-25
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF['bolius_staticdomain'] = [
    'title'            => 'Bolius Static Domain',
    'description'      => '',
    'category'         => 'frontend',
    'author'           => 'Bolius Digital',
    'author_email'     => 'web@bolius.dk',
    'author_company'   => 'Bolius',
    'state'            => 'alpha',
    'version'          => '0.0.1',
    'constraints'      => [
        'depends'   => [
            'typo3' => '6.0.0-11.99.99',
        ],
        'conflicts' => [],
        'suggests'  => [
        ],
    ],
];