services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  Bolius\BoliusStaticdomain\Domain\Repository\SysDomainRepository:
    arguments:
      $connectionPool: '@TYPO3\CMS\Core\Database\ConnectionPool'