services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Bolius\BoliusStaticdomain\Classes\Domain\Repository\SysDomainRepository:
    arguments:
      $connectionPool: '@TYPO3\CMS\Core\Database\ConnectionPool'